name: OSV Scanner

on:
  push:
    branches:
      - main

jobs:
  osv-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install OSV Scanner
        run: pip install osv
      - name: Run OSV Scanner
        run: osv scan
