name: OSV Scanner

on:
  push:
    branches:
      - main

jobs:
  osv-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run OSV Scanner
        uses: google/osv-action@v1
